### ISSUE TITLE
Uncaught TypeError: Cannot read property '$validator' of undefined

### ISSUE THREAD

**Issue by AndreyDolgov** [eregnier/vue2-gmap-custom-marker#11]
Hello,
I'm trying to add this component, but I have a problem.
When I try to add it, I receive
"Uncaught TypeError: Cannot read property '$validator' of undefined
    at mergeData (app.js:2936)
    at VueComponent.mergedDataFn (app.js:2969)
    at initProvide (app.js:5427)
    at VueComponent.Vue._init (app.js:6429)
    at new VueComponent (app.js:6598)
    at createComponentInstanceForVnode (app.js:6110)
    at init (app.js:5931)
    at createComponent (app.js:7408)
    at createElm (app.js:7355)
    at createChildren (app.js:7482)
"
Could you help me please?

**Comment by eregnier** [comment]
Hello,
I have no idea whats appening there. Can you show me your component's code ? (or at least the section around where you use my component).

**Comment by AndreyDolgov** [comment]
I have localized the problem, but have not solved it yet.
This is my code:
```javascript
const vee_config = {
    aria: true,
    classNames: {},
    classes: false,
    delay: 0,
    dictionary: null,
    errorBagName: 'errors', // change if property conflicts
    events: 'input|blur',
    fieldsBagName: 'fields',
    inject: true,
    locale: 'en',
    strict: true,
    validity: false,
};
Vue.use(VeeValidate, vee_config);
Vue.use(VueGoogleMaps, {
    load: {
        key: KEY,
        libraries: 'places', 
        language:LANG,
    },
});
```
As i see - all problem with this option { inject: true} in  vee_config
If i will set vee_config.inject = false, the problem will be solved. But in this case i will to inject $validator in all components myself - thats not good :(

**Comment by eregnier** [comment]
I have absolutly no idea about what is vee and what $validator is used for, but it does not seems related to this component. You may have a side effect with this component, but there is not enough information there to go further in troubleshoting. 

You may be right, with about the $validator that is broking the map. 

Do you still have the issue ? can you explain a bit more, or share code related to the use of the component to help me understand the issue ?

**Edit**: ok i looked a what is vee, but indeed, I cannot help you troubleshooting your code if I do not see how do you use the custom marker component and the relation with vee.

**Comment by eregnier** [comment]
It seems the component is not directly related to this issue. Also close due to inactivity.
