### ISSUE TITLE
Cluster not working when using vue2-gmap-custom-marker in https://github.com/xkjyeah/vue-google-maps

### ISSUE THREAD

**Issue by trunghongoc** [eregnier/vue2-gmap-custom-marker#14]

**Comment by ddedic** [comment]
+1

**Comment by apichaikub** [comment]
+1

**Comment by eregnier** [comment]
Guys ! I am glad to say that I added this feature, cluster now works with the 5.4.3 release. Enjoy :)

**Comment by amirhoseinsalimi** [comment]
Any documentation, buddy?!

**Comment by eregnier** [comment]
> Any documentation, buddy?!

Here it is : https://github.com/eregnier/vue2-gmap-custom-marker/blob/master/README.md#clusters

(I just wrote it 5 minutes ago :writing_hand: )
