### ISSUE TITLE
TypeError: this.$mapPromise.then is not a function

### ISSUE THREAD

**Issue by XzyZachary** [eregnier/vue2-gmap-custom-marker#16]
TypeError: this.$mapPromise.then is not a function

i use your npm package had same error

can you help me ?

**Comment by eregnier** [comment]
Hi, 

please share a trace or a bit of code , so I can investigate. 

Thank you.

**Comment by XzyZachary** [comment]
Sorry, this may be due to my project. I separated and succeeded.
Thank you.

**Comment by vladtanasiedns** [comment]
> Sorry, this may be due to my project. I separated and succeeded.
> Thank you.

What did you separate? How did you solve this issue?

**Comment by Omar-Qalei** [comment]
> > Sorry, this may be due to my project. I separated and succeeded.
> > Thank you.
> 
> What did you separate? How did you solve this issue?

fix from
{src: '~plugins/vue-google-map.js', ssr: true }
with
{src: '~/plugins/vue-google-map.js', ssr: true }

**Comment by XzyZachary** [comment]
> > Sorry, this may be due to my project. I separated and succeeded.
> > Thank you.
> 
> What did you separate? How did you solve this issue?

Sorry, it’s been a long time. Maybe I was later because of a version problem. You can see that he replaced npm named gamp-vue. It turned out to be vue-google-maps. You can consider the solution from the version. hope this helps！
