### ISSUE TITLE
Issue mapping latitude or longitude 0

### ISSUE THREAD

**Issue by JoseGoncalves** [eregnier/vue2-gmap-custom-marker#18]
Found an issue mapping a custom marker with latitude 0 and longitude 0.
With that coordinates the marker is always displayed on the center of the viewport, whatever position that is.
Looking at the source code it seems to me that the issue is due to this code:
```javascript
    lat() {
      return parseFloat(this.marker.lat || this.marker.latitude);
    },
    lng() {
      return parseFloat(this.marker.lng || this.marker.longitude);
    },
```
`this.marker.lat` (or `this.marker.lng`) should not be used to check if the prop is available, because when it's 0, it will return false.
A check like `typeof this.marker.lat === 'undefined'` should be used instead.

**Comment by eregnier** [comment]
Solved. thank you @JoseGoncalves
