### ISSUE TITLE
Updating the zIndex prop

### ISSUE THREAD

**Issue by jsonmaur** [eregnier/vue2-gmap-custom-marker#19]
If I update the `zIndex` prop after the marker has been mounted, it doesn't reflect the update on the map. I'd love to be able to send specific markers to the front or back when there is some overlap.

**Comment by eregnier** [comment]
ok, I'll have a look.

**Comment by popcorn-lille** [comment]
fixed as of v5.5.0

**Comment by eregnier** [comment]
fixed in v5.5.0, enjoy :D

**Comment by jsonmaur** [comment]
Wow, you make quick work! Thanks very much 👍
