### ISSUE TITLE
Cannot read property 'repaint' of undefined

### ISSUE THREAD

**Issue by Flyrell** [eregnier/vue2-gmap-custom-marker#23]
Sometimes on create and/or destroy, the library is throwing `repaint` error specified in title, as it's called inside `setTimeout` and by the time it's called `$overlay` does not exist anymore. 

```javascript
this.$overlay = new Overlay(map);
setTimeout(() => {
    this.$overlay.repaint(); // line: 150
    this.opacity = 1;
}, 100);
```

[Quick fix available in #24](https://github.com/eregnier/vue2-gmap-custom-marker/pull/24)

**Comment by eregnier** [comment]
It should be solved with https://github.com/eregnier/vue2-gmap-custom-marker/commit/9f901a4399fa2aceb399007c9569368ee3cd1685

Package release 5.5.2 contains the changes.

Is it ok on your side @Flyrell ?
