### ISSUE TITLE
Map click triggered on custom marker click

### ISSUE THREAD

**Issue by markmooibroek** [eregnier/vue2-gmap-custom-marker#26]
Heya, really cool plugin. Thanks!

I'm running into a little problem where my map click handler is called then i click a marker. This worked on the normal maps markers but after switching to your custom marker lib Im getting this. 

```html
 <GmapMap
        :zoom="13"
        :center="mapCenter"
        :options="mapOptions"
        map-type-id="terrain"
        ref="gmap"
        class="google-map"
        @click="clearSelection()"
      >
        <GmapCustomMarker
          v-for="(marker, index) in markers"
          :key="index"
          :marker="marker.latLng"
          :offsetY="marker.eta ? 20 : 0"
          alignment="center"
          class="marker"
          @click.native="onMarkerClicked($event, marker)"
        >
          <!-- <GmapMarker :options="markerOptions(marker)" @click="onMarkerClicked($event, marker)"/> -->
          <img :src="markerOptions(marker).icon">
          <div v-if="marker.eta" class="marker-label">
            <span>{{ marker.eta }}</span>
          </div>
        </GmapCustomMarker>
      </GmapMap>
```

I tried `event.preventDefault();` on the marker handler, but thats not working :-)

Any idea on how i should approach this? 

Kind regards

**Comment by eregnier** [comment]
Can you tell me what is the exact problem you have with this code ? any undesired effect ? what do you want to do and what does fails ?
I may help you better with more context :)

**Comment by markmooibroek** [comment]
The undesired effect is that when on clicking on the marker the map click is also detected. I want the click on the marker to add a marker to a selection and if no marker is clicked I want to clear the selection. And because the maps.click is triggered after the marker.click my selection is not working.

Hope this clears it up a bit :-)

**Comment by eregnier** [comment]
Thank you for details. I don't know if there is good patterns for this.

 I have 2 solutions in mind : 

1) do it well by understanding gmap api, handle events properly and so on.
I have no time for this at the moment, but any help would be appreciated :)

2) Do an adhoc handling that I woud do like this :

```javascript
lastMarkerClickTime = + new Date() //save the date in marker click callback
```

and on the map click callback
```javascript
if (+ new Date() - lastMarkerClickTime > 300) {
    /*if one marker was clicked more than 300 ms ago then clear*/ 
   clearMap()
}
```

Is it enought for your needs ?

**Comment by vlada-symphony** [comment]
> I tried event.preventDefault(); on the marker handler, but thats not working :-)

I think what you want is `event.stopPropagation()`, so basically replace `@click.native="onMarkerClicked($event, marker)"` with `@click.native.stop="onMarkerClicked($event, marker)"`.

**Comment by markmooibroek** [comment]
Awesome! Works like a charm. Not too advanced with Vue yet. Thanks for helping!

**Comment by eregnier** [comment]
@vlada-symphony : Perfect :+1:  I did not know this (or just forgot about it). thank you for help and improvements. :heavy_check_mark:

**Comment by cjlaborde** [comment]
@vlada-symphony thank you so much!
Been testing for over an hour to fix a similar issue.
