### ISSUE TITLE
Example Source Code

### ISSUE THREAD

**Issue by robjesus** [eregnier/vue2-gmap-custom-marker#29]
Hi, can you provide the source code from the demo on https://eregnier.github.io/vue2-gmap-custom-marker/dist/

**Comment by eregnier** [comment]
Hi @robjesus,

The code for the demo is in the gh-pages branch : https://github.com/eregnier/vue2-gmap-custom-marker/tree/gh-pages?files=1


Let me know if any toubles. 

Have fun :)
