### ISSUE TITLE
Flickering of markers when you stop dragging the map

### ISSUE THREAD

**Issue by davidkrijgsman** [eregnier/vue2-gmap-custom-marker#3]
Thanks for a nice plugin!

However, I noticed there is some flickering of the custom markers when you stop dragging the map: https://codesandbox.io/s/4w642qo17w

Any thoughts on how to fix that? I tried adding { trailing: false } to the debounce which fixed it, but it causes issues when you programmatically (re)center the map: custom markers are not being repositioned.

**Comment by eregnier** [comment]
Hi,
I did not found how to fix this properly at the moment although I spend many time on this. Unfortunatly, I do not master google maps custom layout enough for now. I would like to fix this, but I may need help.
I'll give another try as soon as I can.

**Comment by eregnier** [comment]
hi @davidkrijgsman.
is this https://github.com/eregnier/vue2-gmap-custom-marker/pull/2 solving your issue ?
this is actually merged and published to npm, you should test easily.

**Comment by eregnier** [comment]
I upgraded the component, no more flickering. Have a look at the demo to see changes https://eregnier.github.io/vue2-gmap-custom-marker/dist/
Is it ok for you ?

**Comment by davidkrijgsman** [comment]
Hi @eregnier, 

Awesome, thanks! I updated the package and it looks like the issue has been resolved. 
If I do encounter any issues I'll let you know, but so far so good :)

**Comment by davidkrijgsman** [comment]
I now have an issue which wasn't there before:

```
Uncaught (in promise) TypeError: Cannot read property 'fromLatLngToDivPixel' of undefined
    at Overlay.draw (gmap-custom-marker.vue:54)
    at gmap-custom-marker.vue:14
```

Although nothing actually breaks in terms of user experience, this error is _sometimes_ displayed in the console when the map and markers are loaded.

**Comment by eregnier** [comment]
I published a fix for this that I could not test, but it should do the trick :https://github.com/eregnier/vue2-gmap-custom-marker/commit/880ea88530f432e74981f7cefdb4cb69747d0156 . Can you let me know if this solved your issue?

**Comment by eregnier** [comment]
Hey, brand new version of the component here. You may give it a try, it works way better now.

**Comment by davidkrijgsman** [comment]
Looks good, thanks for the work! 👍
