### ISSUE TITLE
Old markers don't disappear when my v-for list changes

### ISSUE THREAD

**Issue by Evertt** [eregnier/vue2-gmap-custom-marker#31]
The title says it all. I have a bunch of markers that I render using `v-for="marker in markers"` where `markers` is a computed property.

Whenever the computed property changes, the old markers don't disappear. Only new markers are added, which is not how it should be. This did work properly when I was still using the original `gmap-marker`.

After further debugging I see it has to do with `gmap-cluster`. When I don't use `gmap-cluster` anymore then it works as expected. But according to the readme, these custom markers should also work with `gmap-cluster` right?

**Comment by eregnier** [comment]
Hey,
Yes, the custom markers work with cluster.
I have to test to reproduce your issue to find out a solution.

**Comment by Evertt** [comment]
If you look at my PR, it already gives a partial solution to the problem. Though it doesn't solve it completely yet, it's still buggy.

**Comment by amineyarman** [comment]
I ran into a similar issue.I display or hide markers depending on whether they are within the map bounds. 
What happens is: Let's assume we have a cluster of 4 markers. I move the map and 2 of them disappear from the bounds. Then I come back to have them all in the bounds and go in a cluster view, then the cluster displays 6 markers.
@Evertt Your solution solves the problem somehow.

**Comment by eregnier** [comment]
Ok then, I merge your work Evertt and do a release. I will investigate to find out how to completely fix the problem.
