### ISSUE TITLE
vue2-gmap-custom-marker availabe on unpkg

### ISSUE THREAD

**Issue by KayVeeCodes** [eregnier/vue2-gmap-custom-marker#34]
Hello,

I am currently working on a project built with require.js and I have tried to get the vue2-gmap-custom-marker component from unpkg instead of npm. Unfortunately, when I try to get the package from  [https://unpkg.com/vue2-gmap-custom-marker](https://unpkg.com/vue2-gmap-custom-marker), gets the .vue  part instead of the compiled version!

Any ideas or fixes on this? I could really appreciate it if this awesome tool was available through unpkg.
Thanks in advance!

**Comment by eregnier** [comment]
Well, I think this is related to the way the repository is made. I don't produce any "compiled version". There is only the source file in the repository. I don't know how I should package it for your need. Any suggestions ?

If you can provide me a boilerplate that uses the unpkg source, then I will be able to try to provide a "compiled version" using this I think. https://cli.vuejs.org/guide/build-targets.html

**Comment by eregnier** [comment]
close due to inactivity
