### ISSUE TITLE
Marker offsets completely off with new latest update

### ISSUE THREAD

**Issue by CDBuckmaster** [eregnier/vue2-gmap-custom-marker#39]
As of 5.5.10, all of my markers are appearing about 50% of the map's width to the right of where they are supposed to be.  I'm not sure if it's to do with the relative positioning of other parent elements, but the issue is fixed if I replace the transform with top and left.  

This is without any set offset for the markers, just the position is set.

**Comment by eregnier** [comment]
ok. I have not much elements to find out what's hapenning. I think I have to rollback. I'll do it soon. Sorry for the possibly broken release.

**Comment by eregnier** [comment]
I fixed it. I released v5.6.0 where behavior is back to the previous one and where a new option appears letting user display markers using css. This is described in the documentation / readme :

![image](https://user-images.githubusercontent.com/5399780/79069956-6f452400-7cd2-11ea-96bf-92b4e598072e.png)
