### ISSUE TITLE
Render 4k marker on map with cluster

### ISSUE THREAD

**Issue by ghost** [eregnier/vue2-gmap-custom-marker#42]
My problem is that it takes too long time to render, 
- With vue2-gmap-custom-marker, it takes 2 minutes to complete
![image](https://user-images.githubusercontent.com/19403977/84367420-6acbb780-abfe-11ea-93b3-ce1787792e94.png)

- But with vue-google-maps marker It only takes 10 seconds to complete
![image](https://user-images.githubusercontent.com/19403977/84368324-9c914e00-abff-11ea-9d90-353c73029924.png)

Do you have any way to speed up the display when I use vue2-gmap-custom-marker, please let me know.

**Comment by eregnier** [comment]
Although there is some way to improve the code speed, the rendering time for this component is actually related to the fact that it manages some dom element rendering and data binding whereas the built-in vue gmap marker only display one image element.

If you find out what is bottleneck in this component , we may discuss how to improve it's performances, and I will surely integrate them as much as possible.

**Comment by eregnier** [comment]
Any news for this topic @DE-TamPham ?

**Comment by eregnier** [comment]
If you "only" need  to display image markers, you might serverside generate images and use the built in image marker with server urls solve this problem.

**Comment by eregnier** [comment]
Hey,

I close this issue due to inactivity and because there is no real solution doable in this plugin to improve the render throughput. I also suggested room for improvements for any interested users.

If anyone wants to go further in performance optimization, feel free to reopen the topic.
