### ISSUE TITLE
zIndex 

### ISSUE THREAD

**Issue by RamanSel** [eregnier/vue2-gmap-custom-marker#43]
Hello, 

First of all, thank you for such a great component.

I was wondering if it's possible to adjust the z-index of the gmap-custom-marker to be on top of regular map-info-window? As I Have an issue with gmap-custom-marker not being the top-most level. 

I have a polygon map as a background (each polygon is clickable) and gmap-custom-marker is clickable through when I click on it.

![image](https://user-images.githubusercontent.com/44775362/84431523-6bae1a80-abf9-11ea-88a2-424edb3444d6.png)

**Comment by RamanSel** [comment]
After some research, my real question is, is there a way to select on which map pane gmap-custom-marker is displayed? As I am using it instead of info-window, and want it to be on the same pane as info-window (floatPane).

**Comment by eregnier** [comment]
Hey,

If we look at the code we have in the component 

```javascript
 onAdd() {
          const div = self.$el;
          const panes = this.getPanes();
          //...
          panes.overlayLayer.appendChild(div);
          //...
}
```
So maybe if you use the component.$el you will be able to acheive what you want. (maybe you can use [vue refs](https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements))

Let me know if I am in or if I answered off topic.

Also, I don't know I you saw, but you may interact with the marker z-index using the [appropriate property z-index](https://github.com/eregnier/vue2-gmap-custom-marker#reference) from component documentation reference. Hav you tried this ?

**Comment by eregnier** [comment]
Is it ok for you @RamanSel  ?

**Comment by eregnier** [comment]
Hey @RamanSel,

I close this thread due to inactivity and because this is a very specific edge case where I suggested a solution.
Feel free to reopen if you want to go further on this topic.
