### ISSUE TITLE
HotFix: typeerror: cannot read property 'repaint' of undefined at vuecomponent.zindex

### ISSUE THREAD

**Issue by bwhjakob** [eregnier/vue2-gmap-custom-marker#45]
I'm using a computed property to change the selected-state of a marker.
I also change the z-index so the marker comes on top of the other markers.

I have tracked the issue to somewhere around line 68-70.
A simple check fixes the problem:

zIndex(val) {
  if( this.$overlay )
    this.$overlay.repaint()
  }

**Comment by eregnier** [comment]
hey there.

please show me how to reproduce the error. I don't really want to integrate code if I cannot test it.
You might also do a true pull request, you are already close to it with.

**Comment by eregnier** [comment]
It looks fine finally, I implemented it and there is no visible regressions. 

Thank you for your contribution.
