### ISSUE TITLE
vue-google-maps is no longer maintained

### ISSUE THREAD

**Issue by ethiry** [eregnier/vue2-gmap-custom-marker#46]
Hello,
This project is a plugin for [vue-google-maps](https://github.com/xkjyeah/vue-google-maps) which unfortunately is no longer maintained. This fork: [gmap-vue](https://github.com/diegoazh/gmap-vue) is active though.
In my project I use gmap-vue and vue2-gmap-custom-marker together. It seems to work, but vue2-gmap-custom-marker installs vue-google-maps as a dependency.

Could vue2-gmap-custom-marker depend on gmap-vue instead ?

**Comment by eregnier** [comment]
Yes, that's a good idea. I think however i will only remove this dependency and add information in the readme that this plugin work for both projets. It seems indeed that this plugin is used in many projects now so I won't indirectly add extra processing or misleading content to existing users.

Thank you anyway for pointing me in the right direction :)

Note : I will start by implementing this up to date library in the demo app to try it and validate for myself that it works as expected.

**Comment by eregnier** [comment]
I did some tests. This project is bound to the existing vue-google-map project as it loads some dependencies to this project. This si annoying but  but I have to deal with it.
I guess the cleaner solution is  to create a new major breaking version. 
Howerver I don't know if gmap-vue is mature enough to follow this path now. There is not much stars on it at the moment and it is surely not widely adopted at the moment.

**Comment by ethiry** [comment]
I simply put gmap-vue instead of vue2-google-map both in package.json
and gmap-custom-marker.vue and it seems to work.


Le mar. 10 nov. 2020 à 15:07, eric regnier <notifications@github.com> a
écrit :

**Comment by eregnier** [comment]
This might be because you did not removed the previous node_modules folder and reinstalled all with `npm i`. If you do so, then  the  vue2-google-map plugin sources won't be present anymore, so the install is broken.
Let me know if I miss something.

**Comment by ethiry** [comment]
Indeed I did clear my node_modules folder.
But I referenced this fork in my package.json :
https://github.com/KDS/vue2-gmap-custom-marker
and only gmap-vue is used, not vue2-google-maps.

Le mer. 11 nov. 2020 à 17:15, eric regnier <notifications@github.com> a
écrit :

**Comment by eregnier** [comment]
Hey , I just released V6.0.0 that is now based on vue-gmap. This fork seems legit so I did it finally :).
Thank you for your suggestion, I hope this is all ok for you now.
Les me know if you have any problem with this release. 
Note: I also updated the readme with legacy management notes.
