### ISSUE TITLE
Rotate Marker

### ISSUE THREAD

**Issue by sinangulsever** [eregnier/vue2-gmap-custom-marker#48]
Does your library support marker rotation?

rotation attribute

```vue
<gmap-custom-marker :marker="{lat:selItemCar.position.lat,lng:selItemCar.position.lng}">
  <template>
    <div class="itemCarMarker">
      <div class="plakaPopup">{{ selItemCar.serial }}</div>
      <div class="popupImg"></div>
    </div>
  </template>
</gmap-custom-marker>
```

**Comment by eregnier** [comment]
The library does not provide direct marker rotation system.

However, you can do marker rotation using css. You should look at the [component demo](https://vue2-gmap-custom-marker-demo.utopland.net/) where I added animate.css on markers.

In case you include animate.css the following code should animate marker by only adding classes to the html slot tag.

```vue
<!--include animate.css-->
<gmap-custom-marker :marker="selItemCar.position">
    <div class="itemCarMarker animated infinite pulse">
      <div class="plakaPopup">{{ selItemCar.serial }}</div>
      <div class="popupImg"></div>
    </div>
</gmap-custom-marker>
```
Let me know if this is ok for you :)

**Comment by eregnier** [comment]
It should be solved and there is no more activity. feel free to reopen if needed.
