### ISSUE TITLE
GmapInfoWindow does not work

### ISSUE THREAD

**Issue by JohnyJohny1861** [eregnier/vue2-gmap-custom-marker#49]

**Comment by JohnyJohny1861** [comment]
<GmapCustomMarker
      v-for="(m, index) in markers" :key="index"
      alignment="center"
      :marker="m.position"
      :ref="`gmarker${m.id}`"
      :clickable="true"
      @click="toggleInfoWindow(index)">
  <PinSvg :rotate="m.windowInfo.direction"/>
  <GmapInfoWindow
          v-if="m.windowInfoOpen && m.windowInfo"
          @closeclick="m.windowInfoOpen = false">
      <div class="pm-infoWindow">
          <div>
              <p>Speed:</p>
              <span>{{m.windowInfo.speed}} mph</span>
          </div>
          <div>
              <p>Zip code:</p>
              <span>
                  {{m.windowInfo.zipcode}}
              </span>
          </div>
          <div class="mb-2">
              <p>Location:</p>
              <span style="
                  max-width: 340px;
                  font-size: 15px;
                  line-height: 16px;
              ">
                  {{m.windowInfo.address}}
              </span>
          </div>
          <div>
              <p>Timestamp:</p>
              <span>{{m.windowInfo.timestamp}}</span>
          </div>
          <div>
              <p>Time:</p>
              <span>{{m.windowInfo.time}}</span>
              <span v-if="!m.isFinished"
                    :class="m.windowInfo.isOnline ? 'pm-dot' : 'pm-dotRed'"
              />
          </div>
      </div>
  </GmapInfoWindow>
</GmapCustomMarker>

**Comment by eregnier** [comment]
hey. I can help you , but can you explain what you are trying to do ? please add more context and what are your imports. I cannot really figure it out what you want here without at least one question.

**Comment by eregnier** [comment]
Closed due to inactivity. feel free to reopen.
