### ISSUE TITLE
Cluster image dont work

### ISSUE THREAD

**Issue by giovannidias1** [eregnier/vue2-gmap-custom-marker#52]
I try install cluster but dont work, numbers works fine

![image](https://user-images.githubusercontent.com/6022688/110007782-cc3a3600-7cf9-11eb-9470-6b4664b941f0.png)

**Comment by giovannidias1** [comment]
i solved using ;

`imagePath: "https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m"`

**Comment by eregnier** [comment]
:+1:
