### ISSUE TITLE
How to get extra info in a cluster

### ISSUE THREAD

**Issue by muboeira** [eregnier/vue2-gmap-custom-marker#55]
So I have a cluster of markers on the same position and I need to know at least the ids of each marker inside the cluster. I didn't find any prop to add additional info like a title to the marker so I can get it later when I click the cluster, did I miss something or there is a way to do it?

**Comment by eregnier** [comment]
What do  you want to do exactly ? If the question is : is there some higher level fonction with cluster system then the answer is : not on this plugin (yet ?) . maybe there is something in the [underlaying library (gmap vue)](https://github.com/eregnier/vue2-gmap-custom-marker#clusters) where you can solve your problem.
If you describe me what you want acheive, I might be able to share my point of view on how I would do it.

**Comment by eregnier** [comment]
Hey, muboeira, feel free to share how you solved your issue in case it was solved in order to help other people that might encounter the same problems.

**Comment by muboeira** [comment]
Hello, I actually end up not using clusters but the problem I was having was that if I used native google markers I could put additional info(id, title) on the marker while on the custom marker I couldn't.
