### ISSUE TITLE
Making this library for vue3-google-map

### ISSUE THREAD

**Issue by web-programmer-here** [eregnier/vue2-gmap-custom-marker#57]
Thank you for making this amazing package, the demo looks great. 
Would you be able to make the same component for vue3-google-map? https://github.com/inocan-group/vue3-google-map
thank you

**Comment by eregnier** [comment]
It should be possible. I'll give it a try in a near future (I cannot tell any release date as I did not studied this at the moment).
I'll update this thread if something start to work :)

**Comment by web-programmer-here** [comment]
@eregnier thank you, amazing news to hear this. cant wait to test it out 💯

**Comment by eregnier** [comment]
here we are :partying_face: https://github.com/eregnier/vue3-gmap-custom-marker 
This is brand new, in beta and not much battle tested.
Please test and let me know [on the issue of this project](https://github.com/eregnier/vue3-gmap-custom-marker/issues) what is good , what isn't and other sugestions.
There is some extra work to do to make it works properly I guess, your testing will be appreciated (also PR are appreciated :) )

**Comment by web-programmer-here** [comment]
oh wow @eregnier amazing! thank you, going to test it out now
