### ISSUE TITLE
incompatibility with gmap-vue@3.5.2 cluster and custom marker

### ISSUE THREAD

**Issue by alebacca89** [eregnier/vue2-gmap-custom-marker#58]
How can I use vue2-gmap-custom-marker with last version of gmap-vue?
If I insert the custom marker into gmap cluster it doesn't work. 
The problem seems to be the costructor of the marker. The cluster used in the new version of the gmap-vue wants mmarker as google marker instance and invoke some methods like getLatitude().

**Comment by eregnier** [comment]
ok, I have to check what can be done. I'll try to give a head soon. Thank you for your report

**Comment by sdevore** [comment]
I wonder if one is going to need to change from OverlayView to using MarkerWithLabel https://github.com/googlemaps/js-markerwithlabel

**Comment by eigudewie** [comment]
Any update on this case?
Best regards

**Comment by eregnier** [comment]
@eigudewie , @alebacca89 do you have a minimal sample code to reproduce the issue ?

**Comment by eregnier** [comment]
close due to inactivity
