### ISSUE TITLE
Displaced markers on page change in Nuxt

### ISSUE THREAD

**Issue by vushe** [eregnier/vue2-gmap-custom-marker#59]
Hello,

Thanks for a nice and useful module!
My issue is probably related to SSR rendering in Nuxt. Yet I don't quite understand, why it happens.

1. I load a page with the map. Say, `http://localhost/place-search/`. All markers positions on the map are correct
2. I navigate to another page, say `http://localhost/place-search/place`
3. I navigate back to `http://localhost/place-search/`. <ins>Now the markers are misplaced.</ins> If I hover the map or markers, markers return to the correct places. 

I tried different ways of fixing it in the app (refreshing map and markers, hardcoding marker width and height in HTML markup, etc.), but nothing did work. I found the issue is related to `repaint()` method, where we have a [check](https://github.com/eregnier/vue2-gmap-custom-marker/blob/51a8294c8d2f18f9c33db62fc455e131b4ca2108/gmap-custom-marker.vue#L87) of `offsetWidth` and `offsetHeight` of the marker element. On step 3 both `offsetWidth` and `offsetHeight` are equal to 0. This is the reason why the markers are misplaced.

One way would be to disable position calculation in `repaint()` with an extended check `if (projection && div &&  div.offsetWidth && div.offsetHeight)`, but I'm not sure if it makes sense in 100% of cases. How about a prop that activates this check, e.g. `nuxtMode`? I could make a pull request. 

Or is there any better solution than the one proposed?

P.S. Unfortunately, I can't share code and examples, because the code I develop is proprietary.

**Comment by eregnier** [comment]
Hello,

yes, you can do a PR, I will integrate it if it does not break things :smiley: 

I have no other better idea at the moment.

**Comment by eregnier** [comment]
I merged and published the release. I hope this will help you

**Comment by vushe** [comment]
Thanks @eregnier! It should be safe to go 👍🏻
